### PR TITLE
Add wiki.rtapp.tk and wiki.recaptime.tk certs

### PR DESCRIPTION
**Pull request by Universal-Omega**
To accompany #514

### CODE REVIEW

**Review by MacFan4000 — CHANGES_REQUESTED** [review]
These also have to be added to certs.yaml

**Comment by Universal-Omega** [comment]
> These also have to be added to certs.yaml

I know. I was waiting for #517 to be merged so I can rebase this with no conflict.

**Comment by MacFan4000** [comment]
There is a conflict

**Comment by Universal-Omega** [comment]
> There is a conflict

Fixed.

**Pull request merged**
