### PR TITLE
remove espiral.org cert

### PR DESCRIPTION
**Pull request by Reception123**
Expiring in 3 days from now

CRITICAL - Certificate 'espiral.org' expires in 3 day(s) (Fri 23 Aug 2019 11:59:59 PM GMT +0000).

To be merged before that time if no new cert is provided

### CODE REVIEW

**Comment by Reception123** [comment]
@JohnFLewis Is it okay to do so (without the requester's permission)?

**Comment by JohnFLewis** [comment]
Has anyone contacted Quim to tell him his cert is expiring? If not, that is a serious failure on our behalf.

**Comment by Reception123** [comment]
I've emailed him before and just did again now on his WMF email (the only one I had)

**Comment by JohnFLewis** [comment]
If no response is received, then drop to LE. We're here to provide a flexible service, not a rigid one.

**Comment by Reception123** [comment]
Will do LE if there's still no response

**Pull request closed without merging**
