### PR TITLE
Remove `wizardwiki.wiki` no longer pointing

### PR DESCRIPTION
**Pull request by dmehus**
Hopefully both the commits for this are on here. @Universal-Omega, can you check? When @Reception123 is up, he will just need to delete the private key from the Puppet2 repo, I think.

### CODE REVIEW

**Comment by Universal-Omega** [comment]
Looks like you missed the second comment deleting the key

**Review by Universal-Omega — APPROVED** [review]

**Comment by dmehus** [comment]
> Looks like you missed the second comment deleting the key

Should I check again?

**Comment by Universal-Omega** [comment]
> > Looks like you missed the second comment deleting the key
> 
> Should I check again?
Looks good now

**Comment by dmehus** [comment]
> > > Looks like you missed the second comment deleting the key
> > 
> > 
> > Should I check again?
> > Looks good now

Oh okay, cool. I've unset the custom domain from ManageWiki now, too. So just needs @Reception123 when he's up, I think?

**Comment by Universal-Omega** [comment]
> > > > Looks like you missed the second comment deleting the key
> > > 
> > > 
> > > Should I check again?
> > > Looks good now
> 
> Oh okay, cool. I've unset the custom domain from ManageWiki now, too. So just needs @Reception123 when he's up, I think?

Yep

**Comment by dmehus** [comment]
Thanks, @Pix1234 :)

**Pull request merged**
