### PR TITLE
Per request

### PR DESCRIPTION
**Pull request by dmehus**
Link:  https://meta.miraheze.org/w/index.php?title=User_talk:Reception123&oldid=168212#Redirect_issue

### CODE REVIEW

**Comment by dmehus** [comment]
It seems like this is all we need to do as [the zone file](https://github.com/miraheze/dns/blob/master/zones/pornwiki.org), hosted by us, already has the `@` set up as a wildcard.

**Review by RhinosF1 — CHANGES_REQUESTED** [review]
Needs a certificate

**Comment by Reception123** [comment]
This won't work as there isn't currently an SSL certificate with the name `pornwiki.org`, so that can't be the sslname. I'll have to generate a separate certificate first.

**Comment by dmehus** [comment]
> This won't work as there isn't currently an SSL certificate with the name `pornwiki.org`, so that can't be the sslname. I'll have to generate a separate certificate first.

Ah, crap, the `sslname` is what it makes a wildcard certificate? But wait, how'd we do the `www.pornwiki.org` redirect then? Can't we use the same sslname as that redirect?

**Comment by Reception123** [comment]
done [here](https://github.com/miraheze/ssl/commit/7e0c9b2a41d2b8c2181376a3e87f6524b5fe46b7)

**Comment by Reception123** [comment]
> > This won't work as there isn't currently an SSL certificate with the name `pornwiki.org`, so that can't be the sslname. I'll have to generate a separate certificate first.
> 
> Ah, crap, the `sslname` is what it makes a wildcard certificate? But wait, how'd we do the `www.pornwiki.org` redirect then? Can't we use the same sslname as that redirect?

We did that one because it had a cert: https://github.com/miraheze/ssl/blob/master/certificates/www.pornwiki.org.crt

**Comment by dmehus** [comment]
> done [here](https://github.com/miraheze/ssl/commit/7e0c9b2a41d2b8c2181376a3e87f6524b5fe46b7)

Thanks! :)

**Comment by dmehus** [comment]
> > > This won't work as there isn't currently an SSL certificate with the name `pornwiki.org`, so that can't be the sslname. I'll have to generate a separate certificate first.
> > 
> > 
> > Ah, crap, the `sslname` is what it makes a wildcard certificate? But wait, how'd we do the `www.pornwiki.org` redirect then? Can't we use the same sslname as that redirect?
> 
> We did that one because it had a cert: https://github.com/miraheze/ssl/blob/master/certificates/www.pornwiki.org.crt

Ah, right, that makes sense then. Thanks!

**Pull request merged**
